const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const fs = require('fs');
const path = require('path');
const NodeMediaServer = require('node-media-server');

const app = express();
const server = http.createServer(app);

const io = new Server(server, {
    cors: {
        origin: '*',
        methods: ['GET', 'POST']
    }
});

const PORT = Number(process.env.PORT || 3000);
const RTMP_PORT = Number(process.env.RTMP_PORT || 1935);
const NMS_HTTP_PORT = Number(process.env.NMS_HTTP_PORT || 8000);

const ROOT = __dirname;
const PUBLIC_DIR = path.join(ROOT, 'public');
const MEDIA_DIR = path.join(ROOT, 'media');
const HLS_DIR = path.join(MEDIA_DIR, 'hls');
const DATA_DIR = path.join(ROOT, 'data');
const USERS_FILE = path.join(DATA_DIR, 'users.json');

for (const dir of [PUBLIC_DIR, MEDIA_DIR, HLS_DIR, DATA_DIR]) {
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
}

if (!fs.existsSync(USERS_FILE)) {
    fs.writeFileSync(USERS_FILE, '[]', 'utf8');
}

app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true }));

/* =========================================
   USERS
========================================= */

function readUsers() {
    try {
        return JSON.parse(
            fs.readFileSync(USERS_FILE, 'utf8')
        );
    } catch {
        return [];
    }
}

function saveUsers(users) {
    fs.writeFileSync(
        USERS_FILE,
        JSON.stringify(users, null, 2),
        'utf8'
    );
}

/* =========================================
   STATIC
========================================= */

app.use(express.static(PUBLIC_DIR));

/*
   HLS files generated by the streaming server
   are also served by Express.
*/
app.use(
    '/hls',
    express.static(HLS_DIR, {
        setHeaders: (res, file) => {

            res.setHeader(
                'Access-Control-Allow-Origin',
                '*'
            );

            res.setHeader(
                'Cache-Control',
                'no-cache, no-store, must-revalidate'
            );

            if (file.endsWith('.m3u8')) {
                res.setHeader(
                    'Content-Type',
                    'application/vnd.apple.mpegurl'
                );
            }

            if (file.endsWith('.ts')) {
                res.setHeader(
                    'Content-Type',
                    'video/mp2t'
                );
            }
        }
    })
);

/* =========================================
   REGISTER
========================================= */

app.post('/api/register', (req, res) => {

    const username =
        String(req.body.username || '').trim();

    const password =
        String(req.body.password || '');

    if (username.length < 2) {
        return res.json({
            ok: false,
            message: 'Username is too short'
        });
    }

    if (password.length < 3) {
        return res.json({
            ok: false,
            message: 'Password is too short'
        });
    }

    const users = readUsers();

    const exists = users.some(
        user =>
            user.username.toLowerCase() ===
            username.toLowerCase()
    );

    if (exists) {
        return res.json({
            ok: false,
            message: 'Username already exists'
        });
    }

    users.push({
        username,
        password,
        createdAt: Date.now()
    });

    saveUsers(users);

    console.log(
        `[REGISTER] ${username}`
    );

    res.json({
        ok: true,
        username
    });
});

/* =========================================
   LOGIN
========================================= */

app.post('/api/login', (req, res) => {

    const username =
        String(req.body.username || '').trim();

    const password =
        String(req.body.password || '');

    const users = readUsers();

    const user = users.find(
        item =>
            item.username.toLowerCase() ===
            username.toLowerCase() &&
            item.password === password
    );

    if (!user) {
        return res.json({
            ok: false,
            message: 'Wrong username or password'
        });
    }

    console.log(
        `[LOGIN] ${user.username}`
    );

    res.json({
        ok: true,
        username: user.username
    });
});

/* =========================================
   STATUS
========================================= */

app.get('/api/status', (req, res) => {

    res.json({
        ok: true,
        online: onlineUsers.size,
        players: players.size,
        stream: {
            url: '/hls/ews/index.m3u8'
        },
        time: Date.now()
    });
});

/* =========================================
   ONLINE USERS
========================================= */

const onlineUsers = new Map();

/* =========================================
   PLAYERS
========================================= */

const players = new Map();

function onlineList() {
    return Array.from(
        onlineUsers.values()
    );
}

function playerList() {
    return Array.from(
        players.values()
    );
}

function sendOnline() {
    io.emit(
        'online-users',
        onlineList()
    );
}

function sendPlayers() {
    io.emit(
        'players-state',
        playerList()
    );
}

/* =========================================
   SOCKET.IO
========================================= */

io.on('connection', socket => {

    console.log(
        `[SOCKET] ${socket.id}`
    );

    /* -------------------------------------
       JOIN
    ------------------------------------- */

    socket.on('join', data => {

        const username =
            String(
                data?.username || 'Guest'
            ).trim();

        const language =
            String(
                data?.language || 'en'
            ).trim();

        if (!username) return;

        socket.username = username;
        socket.language = language;

        onlineUsers.set(
            socket.id,
            {
                id: socket.id,
                username,
                language
            }
        );

        players.set(
            socket.id,
            {
                id: socket.id,
                username,
                x: 0,
                y: 0,
                z: 8,
                ry: 0,
                jumping: false
            }
        );

        socket.emit(
            'joined',
            {
                ok: true,
                username
            }
        );

        socket.emit(
            'players-state',
            playerList()
        );

        socket.broadcast.emit(
            'player-joined',
            {
                id: socket.id,
                username
            }
        );

        socket.broadcast.emit(
            'system-message',
            {
                text:
                    `${username} entered EWS SESSIONS`,
                ts: Date.now()
            }
        );

        sendOnline();
        sendPlayers();

        console.log(
            `[JOIN] ${username}`
        );
    });

    /* -------------------------------------
       REQUEST ONLINE
    ------------------------------------- */

    socket.on(
        'request-online',
        () => {

            socket.emit(
                'online-users',
                onlineList()
            );

            socket.emit(
                'players-state',
                playerList()
            );
        }
    );

    /* -------------------------------------
       PLAYER POSITION
    ------------------------------------- */

    socket.on(
        'player-move',
        data => {

            const player =
                players.get(socket.id);

            if (!player) return;

            const x = Number(data?.x);
            const y = Number(data?.y);
            const z = Number(data?.z);
            const ry = Number(data?.ry);

            if (
                !Number.isFinite(x) ||
                !Number.isFinite(y) ||
                !Number.isFinite(z)
            ) {
                return;
            }

            player.x = x;
            player.y = y;
            player.z = z;

            if (Number.isFinite(ry)) {
                player.ry = ry;
            }

            player.jumping =
                Boolean(data?.jumping);

            socket.broadcast.emit(
                'player-move',
                player
            );
        }
    );

    /* -------------------------------------
       CHAT
    ------------------------------------- */

    socket.on(
        'chat-message',
        data => {

            if (!socket.username) return;

            const text =
                String(
                    data?.text || ''
                ).trim();

            if (!text) return;

            if (text.length > 500) return;

            io.emit(
                'chat-message',
                {
                    user: socket.username,
                    username: socket.username,
                    text,
                    original: text,
                    ts: Date.now()
                }
            );
        }
    );

    /* -------------------------------------
       LANGUAGE
    ------------------------------------- */

    socket.on(
        'language-change',
        language => {

            const user =
                onlineUsers.get(
                    socket.id
                );

            if (!user) return;

            user.language =
                String(
                    language || 'en'
                );

            onlineUsers.set(
                socket.id,
                user
            );

            sendOnline();
        }
    );

    /* -------------------------------------
       DISCONNECT
    ------------------------------------- */

    socket.on(
        'disconnect',
        reason => {

            const user =
                onlineUsers.get(
                    socket.id
                );

            if (!user) return;

            console.log(
                `[OFFLINE] ${user.username} | ${reason}`
            );

            onlineUsers.delete(
                socket.id
            );

            players.delete(
                socket.id
            );

            socket.broadcast.emit(
                'player-left',
                {
                    id: socket.id
                }
            );

            socket.broadcast.emit(
                'system-message',
                {
                    text:
                        `${user.username} left EWS SESSIONS`,
                    ts: Date.now()
                }
            );

            sendOnline();
            sendPlayers();
        }
    );
});

/* =========================================
   NODE MEDIA SERVER
========================================= */

try {

    const nmsConfig = {

        rtmp: {
            port: RTMP_PORT,
            chunk_size: 60000,
            gop_cache: true,
            ping: 30,
            ping_timeout: 60
        },

        http: {
            port: NMS_HTTP_PORT,
            mediaroot: MEDIA_DIR,
            allow_origin: '*'
        },

        trans: {

            ffmpeg:
                process.env.FFMPEG_PATH ||
                'ffmpeg',

            tasks: [
                {
                    app: 'ews',

                    hls: true,

                    hlsFlags:
                        '[hls_time=2:hls_list_size=6:hls_flags=delete_segments]',

                    dash: false
                }
            ]
        }
    };

    const nms =
        new NodeMediaServer(
            nmsConfig
        );

    nms.run();

    console.log(
        `[NMS] RTMP ${RTMP_PORT}`
    );

    console.log(
        `[NMS] HLS ${NMS_HTTP_PORT}`
    );

} catch (error) {

    console.log(
        '[NMS]',
        error.message
    );

    console.log(
        '[NMS] Website continues without media server'
    );
}

/* =========================================
   ROOT
========================================= */

app.get('/', (req, res) => {

    res.sendFile(
        path.join(
            PUBLIC_DIR,
            'index.html'
        )
    );
});

/* =========================================
   404
========================================= */

app.use((req, res) => {

    if (
        req.method === 'GET' &&
        req.accepts('html')
    ) {

        return res.sendFile(
            path.join(
                PUBLIC_DIR,
                'index.html'
            )
        );
    }

    res.status(404).json({
        ok: false,
        message: 'Not found'
    });
});

/* =========================================
   SERVER
========================================= */

server.listen(
    PORT,
    '0.0.0.0',
    () => {

        console.log('');
        console.log(
            '================================'
        );
        console.log(
            '       EWS SESSIONS'
        );
        console.log(
            '       SERVER READY'
        );
        console.log(
            '================================'
        );
        console.log(
            `PORT: ${PORT}`
        );
        console.log(
            `RTMP: ${RTMP_PORT}`
        );
        console.log(
            `HLS: ${NMS_HTTP_PORT}`
        );
        console.log(
            '================================'
        );
        console.log('');
    }
);

process.on(
    'SIGINT',
    () => process.exit(0)
);

process.on(
    'SIGTERM',
    () => process.exit(0)
);